export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SUCCESS_REQUEST = "USER_SUCCESS_REQUEST";
export const USER_FAIL_REQUEST = "USER_FAIL_REQUEST";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_CLEAR = "USER_REGISTER_CLEAR";

export const USER_VERIFY_OTP_REQUEST = "USER_VERIFY_OTP_REQUEST";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAIL = "USER_VERIFY_OTP_FAIL";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_CLEAR = "USER_DETAIL_CLEAR";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_ADDRESS_REQUEST = "USER_ADDRESS_REQUEST";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
export const USER_ADDRESS_FAIL = "USER_ADDRESS_FAIL";
export const USER_ADDRESS_RESET = "USER_ADDRESS_RESET";

export const USER_ADD_ADDRESS_REQUEST = "USER_ADD_ADDRESS_REQUEST";
export const USER_ADD_ADDRESS_SUCCESS = "USER_ADD_ADDRESS_SUCCESS";
export const USER_ADD_ADDRESS_FAIL = "USER_ADD_ADDRESS_FAIL";
export const USER_ADD_ADDRESS_RESET = "USER_ADD_ADDRESS_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
